'use client';

import type { SessionSummary } from '@path-connect/shared';

interface ConversationSummaryProps {
  summary: SessionSummary;
}

export function ConversationSummary({ summary }: ConversationSummaryProps) {
  return (
    <div className="card mb-4">
      <div className="flex items-center gap-3 mb-3">
        <div className="w-8 h-8 rounded-lg bg-primary-50 flex items-center justify-center">
          <svg className="w-4 h-4 text-primary-600" fill="currentColor" viewBox="0 0 20 20">
            <path fillRule="evenodd" d="M18 10c0 3.866-3.582 7-8 7a8.841 8.841 0 01-4.083-.98L2 17l1.338-3.123C2.493 12.767 2 11.434 2 10c0-3.866 3.582-7 8-7s8 3.134 8 7zM7 9H5v2h2V9zm8 0h-2v2h2V9zM9 9h2v2H9V9z" clipRule="evenodd" />
          </svg>
        </div>
        <div>
          <h2 className="font-semibold text-gray-900">Conversation Summary</h2>
          <p className="text-xs text-gray-400">Auto-generated by AI</p>
        </div>
      </div>
      <p className="text-sm text-gray-600 leading-relaxed">{summary.conversationSummary}</p>
    </div>
  );
}
